#+TITLE: Stewart Platforms
:DRAWER:
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./css/readtheorg.css"/>
#+HTML_HEAD: <script src="./js/jquery.min.js"></script>
#+HTML_HEAD: <script src="./js/bootstrap.min.js"></script>
#+HTML_HEAD: <script src="./js/jquery.stickytableheaders.min.js"></script>
#+HTML_HEAD: <script src="./js/readtheorg.js"></script>

#+PROPERTY: header-args:latex  :headers '("\\usepackage{tikz}" "\\usepackage{import}" "\\import{$HOME/Cloud/tikz/org/}{config.tex}")
#+PROPERTY: header-args:latex+ :imagemagick t :fit yes
#+PROPERTY: header-args:latex+ :iminoptions -scale 100% -density 150
#+PROPERTY: header-args:latex+ :imoutoptions -quality 100
#+PROPERTY: header-args:latex+ :results raw replace :buffer no
#+PROPERTY: header-args:latex+ :eval no-export
#+PROPERTY: header-args:latex+ :exports both
#+PROPERTY: header-args:latex+ :mkdirp yes
#+PROPERTY: header-args:latex+ :output-dir figs
:END:

* Introduction                                                       :ignore:
The goal of this project is to provide a Matlab/Simscape Toolbox to study Stewart platforms.

The project is divided into several section listed below.

* Simulink Project ([[file:simulink-project.org][link]])
The project is managed with a *Simulink Project*.
Such project is briefly presented [[file:simulink-project.org][here]].

* Stewart Platform Architecture Definition ([[file:stewart-architecture.org][link]])
The way the Stewart Platform is defined is explained [[file:stewart-architecture.org][here]].

All the geometrical parameters are defined including:
- Definition of the location of the frames
- Location/orientation of the limbs
- Size/inertia of the platforms and the limbs

Other parameters are also defined such as:
- Stiffness and damping of the struts
- Rest position of the Stewart platform

* Simscape Model of the Stewart Platform ([[file:simscape-model.org][link]])
The Stewart Platform is then modeled using [[https://www.mathworks.com/products/simscape.html][Simscape]].

The way to model is build and works is explained [[file:simscape-model.org][here]].

* Kinematic Analysis ([[file:kinematic-study.org][link]])
From the defined geometry of the Stewart platform, we can perform static analysis such as:
- *Jacobian Analysis* that links the velocity of each limb to the velocity of the mobile platform
- *Static Forces Analysis* that links the forces applied by each limb to the resulting force/torque applied to the mobile platform

From the strut stiffness, we can also perform a *Stiffness Analysis* that consists of determining the Stiffness matrix and Compliance matrix of the Stewart platform from the geometry.

All these analysis are described [[file:kinematic-study.org][here]].

* Identification of the Stewart Dynamics ([[file:identification.org][link]])
The Dynamics of the Stewart platform can be identified using the Simscape model.

It is possible to:
- Determine the dynamics from the actuators to the various sensors included in the Stewart platform
- Extract State Space models for further analysis / control synthesis
- Extract the Resonant Frequencies, Modal Damping, and associated Mode Shapes

The code that is used for identification is explained [[file:identification.org][here]].
 
* Control
The use of active control for Stewart platforms is a wide subject.
Many aspect can be studied.

The sensors used is of primary important. We can have:
- Sensors located in each strut: relative motion, force sensor, inertial sensor
- Sensors measuring the relative motion between the fixed base and the mobile platform
- Inertial sensors located on the mobile platform

The control objective can also vary:
- Reference Tracking
- Active Damping
- Vibration Isolation

The Control for Stewart platforms is here studied in the following files:
- *Active Damping* ([[file:control-active-damping.org][link]]).
  The use of different sensors are compared for active damping:
  - Inertial Sensor in each strut or fixed to the mobile platform
  - Force Sensor in each strut
  - Relative Motion Sensor in each strut
- *Motion Control* ([[file:control-tracking.org][link]]).
  Different control architectures (centralized and decentralized) are compared for the position control of the Stewart platform.
- *Vibration Isolation* ([[file:control-vibration-isolation.org][link]])

* Cubic Configuration ([[file:cubic-configuration.org][link]])
The cubic configuration is a special class of Stewart platform that has interesting properties.

These properties are studied in [[file:cubic-configuration.org][this]] document.

* Bibliography ([[file:bibliography.org][link]])
Many text books, PhD thesis and articles related to parallel robots and Stewart platforms are gathered in [[file:bibliography.org][this]] document.
